### ISSUE TITLE
More then 5 sec waiting before share message appear

### ISSUE THREAD

**Issue by ufgo** [britzl/defold-sharing#15]
Defold 1.2.174
Android Miui 11.05

When i try to share image it take more then 5 sec.
I compared two different apps, first on defold and last other. In last app speed 1.7 sec. Then i compared file sizes and for first its was 1 mb and 320 kb for last. 
Also i testing other app made on defold with .png file size 56 kb and speed for "share" "message appears 3.2 sec.
![IMG_20201102_161259](https://user-images.githubusercontent.com/21050233/97856362-5fe8ff00-1d26-11eb-804e-63e30640b8af.jpg)

**Comment by britzl** [comment]
I am unsure of why this happens. The share popup is shown instantly on my Android device. Have you tried other devices?

**Comment by AGulev** [comment]
I think it depends on number applications on device or something like that. On my device it's instantly too, but Alex reported me that he has the same issue. I added a spiner to show user that app is thinking and hide it when app gains focus.

**Comment by britzl** [comment]
Good point! I think it might be possible to limit what kind of apps that are shown somehow.
