### ISSUE TITLE
share.image() causes crash with gl error 1282: invalid operation

### ISSUE THREAD

**Issue by jm1175** [britzl/defold-sharing#17]
In Defold 1.2.181 the share.image() function causes a crash with the following error:

OpenGLSetVertexBufferData(1302): gl error 1282: invalid operation
Assertion failed: (0), function OpenGLSetVertexBufferData, file ../src/opengl/graphics_opengl.cpp, line 1302.

I'm testing on the Defold simulator (Mac OS Big Sur 11.2.3). The crash happens as soon as I select an app to share from the dropdown menu. It works as expected in Defold 1.2.179 but not the latest two releases.

**Comment by britzl** [comment]
Thanks. I'll take a look.

**Comment by britzl** [comment]
This is a problem with the screenshot extension, not the sharing extension:

https://github.com/britzl/defold-screenshot/issues/14
