### ISSUE TITLE
Uncaught translation error: com.android.dx.cf.code.SimException

### ISSUE THREAD

**Issue by jm1175** [britzl/defold-sharing#18]
I am getting the following warnings and error from the sharing extension when bundling for Android:

warning: [options] bootstrap class path not set in conjunction with -source 6
warning: [options] source value 6 is obsolete and will be removed in a future release
warning: [options] target value 1.6 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: /tmp/job18040778050683374763/upload/gpgs/src/java/com/defold/gpgs/GpgsJNI.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /tmp/job18040778050683374763/upload/gpgs/src/java/com/defold/gpgs/GpgsJNI.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in androidx.emoji2.text.EmojiCompatInitializer$BackgroundDefaultLoader.load:(Landroidx/emoji2/text/EmojiCompat$MetadataRepoLoaderCallback;)V: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)

I didn't have this issue with Defold 1.2.179, only in the more recent versions but when I go back to 1.2.179 to bundle the project the warnings and error persist.

**Comment by britzl** [comment]
Are you using other extensions as well? And which version of Defold are you using?

**Comment by britzl** [comment]
The problem could be related to our use of the dx tool instead of the newer d8 tool. We have a task to upgrade to d8: https://github.com/defold/defold/issues/4658

We plan to address this soon.

**Comment by jm1175** [comment]
Yes these are the extensions I'm using:

https://github.com/britzl/defold-sharing/archive/master.zip,
https://github.com/britzl/defold-screenshot/archive/master.zip,
https://github.com/animonger/extension-gamekit/archive/master.zip,
https://github.com/defold/extension-gpgs/archive/master.zip,
https://github.com/defold/extension-googleplayinstant/archive/master.zip,
https://github.com/subsoap/defos/archive/master.zip,
https://github.com/defold/extension-iap/archive/master.zip,
https://github.com/Lerg/extension-admob/archive/master.zip

When I remove the sharing extension the issue is gone and it bundles successfully. I'm using Defold 1.2.179, but I also get the error in Defold 1.2.182.

Do you know of any way I can get this working right now? It's strange how I didn't have the issue before when using Defold 1.2.179 but after updating to the latest version and then going back to 1.2.179 the issue remains. Is there something that got changed in the project files that causes the issue to persist?

**Comment by britzl** [comment]
> Do you know of any way I can get this working right now? It's strange how I didn't have the issue before when using Defold 1.2.179 but after updating to the latest version and then going back to 1.2.179 the issue remains. Is there something that got changed in the project files that causes the issue to persist?

Try removing the build and .internal folders. Do Project->Fetch Libraries again and then try to bundle.

**Comment by jm1175** [comment]
I tried it but no luck unfortunately. I also just tried creating a brand new Defold project (1.2.179), adding only the sharing extension and then doing a bundle but it still has the same warnings and error.

**Comment by AGulev** [comment]
PR that should fix it (works for me) https://github.com/britzl/defold-sharing/pull/19/files
