### ISSUE TITLE
Android.manifest error

### ISSUE THREAD

**Issue by Dragosha** [britzl/defold-sharing#2]
Tryed to add `<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="{{android.package}}.fileprovider"
            android:grantUriPermissions="true"
            android:exported="false">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths" />
        </provider>` to manifest
got en build error:
![2017-11-07_13-40-50](https://user-images.githubusercontent.com/842807/32484420-9278a450-c3c1-11e7-99cb-9d1d4763339d.png)

**Comment by britzl** [comment]
Sorry, I completely missed this issue report. Is this still a problem for you @Dragosha ?

**Comment by Dragosha** [comment]
@britzl 
As I remember we solved this issue after moving "share" extension to project folder from project depency.

**Comment by Lerg** [comment]
It's still an issue. Defold doesn't copy resources from the extension when AndroidManifest check is made. Even more, if you copy the resource file into your project and leave the extension as a dependency, Defold will show an error of conflicting resource files.
Similar stuff happens with AdMob extension.

**Comment by britzl** [comment]
This is on our radar and will be fixed fairly soon (within 2-4 releases, depending on other priorities)

**Comment by britzl** [comment]
Fixed
