### ISSUE TITLE
Sharing Error: TypeError: Cannot read properties of null (reading ‘1’)

### ISSUE THREAD

**Issue by Luciatar** [britzl/defold-sharing#23]
Sharing fails with this error message:
Sharing Error: TypeError: Cannot read properties of null (reading ‘1’)

The rest of the app still works. No crashes.

[sharing_min_issue.zip](https://github.com/britzl/defold-sharing/files/9147681/sharing_min_issue.zip)

**Comment by britzl** [comment]
How are you testing this? When I'm testing locally in a non secure context I get `Sharing Error: navigator.share is not supported`. I believe you have to test from a page served over https.

**Comment by Luciatar** [comment]
hmm im not sure I just build html5 in defold.
![share_test_build](https://user-images.githubusercontent.com/46559798/180950996-307c044a-2ce3-4bef-90a2-54cd9e5266e7.png)

**Comment by britzl** [comment]
On which OS? Windows? macOS?

I tested on Chrome Version 103.0.5060.134. It looks like you are using Chrome 101.

I'll test again.

**Comment by Luciatar** [comment]
I'm on windows 10

**Comment by britzl** [comment]
<img width="626" alt="Screenshot 2022-07-26 at 11 32 44" src="https://user-images.githubusercontent.com/1300688/180974368-103507ed-7085-4013-9398-09c0f7d842e2.png">

**Comment by Luciatar** [comment]
![caniuse](https://user-images.githubusercontent.com/46559798/181179509-9131b57e-03da-4c8d-8e96-4139040a8c0d.png)
I dont really understand it should work on chrome 103 on all platforms

**Comment by britzl** [comment]
> I dont really understand it should work on chrome 103 on all platforms. Are you on mac?
> I deployed to the site so there is no issue with https:
> https://sharingminissue.netlify.app/

Yes, I'm on macOS and latest Chrome. When testing from the URL above I still get:

```
Sharing Error: navigator.share is not supported
```

Ah, here we go. Only supported on Windows... doh

<img width="488" alt="Screenshot 2022-07-27 at 13 11 37" src="https://user-images.githubusercontent.com/1300688/181233411-9d2692a1-0673-439c-9591-63fed118ec8c.png">

**Comment by Luciatar** [comment]
I believe you should be able to test on Safari

**Comment by britzl** [comment]
> I believe you should be able to test on Safari

Ah, yes, that is true! I'll take a look later today or tomorrow.
