### ISSUE TITLE
iOS crash

### ISSUE THREAD

**Issue by Dragosha** [britzl/defold-sharing#4]
Tried to use this NE in my game on iOS and got a crash. App just closes. Have no any errors in Defold console. This happens each time after call share.text(...).

All works correct on Android.
----
iOS 11.2.6, iPad mini 2

**Comment by britzl** [comment]
What does the XCode console show when you select the device and run and reproduce the crash?

**Comment by britzl** [comment]
Is it a hard crash you're getting or "only" inside the extension somehow? Does the entire app close?

**Comment by Dragosha** [comment]
Yes, it is hard crash, app is totaly closing.

**Comment by Dragosha** [comment]
@britzl 
messages from console before crash:

*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIActivityViewController (<UIActivityViewController: 0x14291ca00>). In its current trait environment, the modalPresentationStyle of a UIActivityViewController with this style is UIModalPresentationPopover. You must provide location information for this popover through the view controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the view controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'
*** First throw call stack:
(0x181287164 0x1804d0528 0x18b488fdc 0x18ab8fb84 0x18ab8d648 0x18aaafaa8 0x18aaa2e5c 0x18a834464 0x18122ecdc 0x18122c694 0x18114cc78 0x10062e2c8 0x100518850 0x1004c189c 0x1005183a8 0x1004c215c 0x1004c1fe8 0x1004c2270 0x180c6c56c)

next message INFO:CRASH: Successfully wrote Crashdump to file:
[LookYourLoot-2018-04-24-120941.crash.log](https://github.com/britzl/defold-sharing/files/1941588/LookYourLoot-2018-04-24-120941.crash.log)

**Comment by britzl** [comment]
Thanks. This is probably helpful. I'll look into this issue soon.

**Comment by britzl** [comment]
I don't have an iPad to test on here at home, but I have something ready on a branch if you're willing to test yourself: https://github.com/britzl/defold-sharing/tree/ipad_sharing

(based on findings here: http://pinkstone.co.uk/how-to-share-things-with-a-uiactivityviewcontroller/)

**Comment by Dragosha** [comment]
@britzl I've tested now and it works super-duper correctly! No crash on ipad now. Thanks!

**Comment by britzl** [comment]
Excellent, thank you for the update! I'll go ahead and release the new version then.

**Comment by britzl** [comment]
https://github.com/britzl/defold-sharing/releases/tag/1.3.1
